
# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

# include: package:flutter_lints/flutter.yaml

# linter:
#   rules:

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
