name: flutter_pokemon_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.6
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_svg: ^1.1.5
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  hooks_riverpod: ^1.0.4
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  like_button: ^2.0.4
  simple_logger: ^1.9.0+1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_gen_runner:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.6
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.19.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_gen:
  output: lib/utils/gen/

flutter_native_splash:
  color: '#FFFFFF'
  image: 'assets/splash_icons/icon.png'
  fullscreen: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
